# +-------------------------------------------------------------------------+
# | en/main.yaml - English Translations                                     |
# +-------------------------------------------------------------------------+

demo:
  hello: Hey {name}
