# --------------------------------------------- #
#                                               #
# MAIN.YAML                                     #
#                                               #
# In this file you define the main config       #
# of your application.                          #
#                                               #
# --------------------------------------------- #

# Logging
# ---------------------------------------------
logging:
  enabled: true
  # Wanted log level: debug, info, notice, warning, error, critical, alert, emergency
  level: debug
  # Also log php errors (instead of default log file)?
  errors: true
  # Chmod for log files (optional)
  file_permissions: 0664

# Session
# ---------------------------------------------
session:
  # Expiration in minutes
  expire: 1440
  # Name of session
  name: charm
  # Default language for translations
  default_language: en

# Localization
# ---------------------------------------------
local:
  timezone:  Europe/Berlin
  language:  de_DE.utf8
  shortlang: de
  # Timestamps for displaying
  timestamps:
    date:          '%d. %B %Y'
    dateshort:     '%d.%m.%Y'
    datetimeshort: '%d.%m.%Y %H:%M'
  # Text formatting
  formatting:
    decimal: ','
    thousands: '.'

# Debug
# ---------------------------------------------
debug:
  # Debug mode?
  debugmode: true
  # Show debug bar on views
  show_debugbar: true
  # Log debugbar data for a history
  log_debugbar: true
  # Display exception instead of error_style when in debug mode? (default: true)
  exceptions: true
  # The local base path to the project for Whoops page
  base_path: '/home/foobar/projects/Charm'
  # The editor to open files in for Whoops page
  # Available: sublime, textmate, emacs, macvim, phpstorm, idea,
  #            vscode, atom, espresso, xdebug, netbeans
  editor: atom

# Storage
# ---------------------------------------------
storages:
  # var and data are already available. Add your own ones
  #sample:
  #  type: 'local'
  #  path: ''

# Output
# ---------------------------------------------
output:
  # JSON output
  json:
    # Output json formatted in multiple lines (true) or in single line (false)?
    pretty: true
  # Error style (default, view, json, exception)
  error_style: view
  # Error view template
  error_view: '_base.error'

# Guard auth system
# ---------------------------------------------
guard:
  # Enable auth system (guard)?
  enabled: true
  # User class with namespace to use for authentication etc.
  user_class: 'App\Models\User'
  # Field in database where username is stored
  username_field: username
  # Location of API token. Can be field of user table of Token class
  token_location: api_token
  # Two factor auth field (false for disable 2fa auth)
  2fa_field: false
  # The master password for all logins (false for disabling)
  master_password: false
  # Unique authentication salt
  auth_salt: 'REPLACE-WITH-YOUR-OWN'
  # The route to redirect to in case of no auth ("guard:auth" route filter)
  no_auth_route: no_auth

# BarBeQueue queue system

bbq:
  # Name prefix for redis keys
  name: charm-bbq