# --------------------------------------------- #
#                                               #
# MAIN.YAML                                     #
#                                               #
# In this file you define the main config       #
# of your application.                          #
#                                               #
# --------------------------------------------- #

# Logging
# ---------------------------------------------
logging:
  enabled: true
  # Wanted log level: debug, info,
  level: debug
  # Also log php errors (instead of default log file)?
  errors: true

# Session
# ---------------------------------------------
session:
  # Expiration in minutes
  expire: 1440
  # Name of session
  name: charm

# Localization
# ---------------------------------------------
local:
  timezone:  Europe/Berlin
  language:  de_DE.utf8
  shortlang: de
  # Timestamps for displaying
  timestamps:
    date:          '%d. %B %Y'
    dateshort:     '%d.%m.%Y'
    datetimeshort: '%d.%m.%Y %H:%M'
  # Text formatting
  formatting:
    decimal: ','
    thousands: '.'

# Debug
# ---------------------------------------------
debug:
  # Debug mode?
  debugmode: true
  # Show debug bar on views
  show_debugbar: true
  # Display exception instead of error_style when in debug mode? (default: true)
  exceptions: true

# Output
# ---------------------------------------------
output:
  # JSON output
  json:
    # Output json formatted in multiple lines (true) or in single line (false)?
    pretty: true
  # Error style (default, view, json, exception)
  error_style: view
  # Error view template
  error_view: '_base.error'

# Guard auth system
# ---------------------------------------------
guard:
  # Enable auth system (guard)?
  enabled: true
  # User class with namespace to use for authentication etc.
  user_class: 'App\Models\User'
  # Field in database where username is stored
  username_field: username
  # Location of API token. Can be field of user table of Token class
  token_location: api_token
  # Two factor auth field (false for disable 2fa auth)
  2fa_field: false
  # The master password for all logins (false for disabling)
  master_password: false
  # Unique authentication salt
  auth_salt: 'REPLACE-WITH-YOUR-OWN'

# BarBeQueue queue system

bbq:
  # Name prefix for redis keys
  name: charm-bbq