# --------------------------------------------- #
#                                               #
# MODULES.YAML                                  #
#                                               #
# In this file you define all additional        #
# modules which should be loaded.               #
#                                               #
# Just provide the class name of the module     #
# binding with full namespace.                  #
#                                               #
# --------------------------------------------- #

modules:
  # Adds debug bar to views when debug mode is enabled
  - \Charm\DebugBar\DebugBar
  # General data exporter to csv, xlsx, ...
  - \Charm\DataExporter\DataExporter
  # Cron system
  - \Charm\Crown\Crown
  # Queue system
  - \Charm\Barbequeue\Queue